### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by abjeroen** [MarcoLucidi01/ytcast#7] opened 2022-05-03 08:29 UTC
hi, I can't get this installed. With make install i get the following error:

# runtime/cgo
during RTL pass: ira
gcc_context.c: In function ‘_cgo_release_context’:
gcc_context.c:21:1: internal compiler error: Segmentation fault
   21 | }
      | ^
0x76a20d9f ???
	../sysdeps/unix/sysv/linux/arm/sigrestorer.S:64
0x76a08bdf __libc_start_main
	./csu/libc-start.c:308

**Comment by MarcoLucidi01** [comment] 2022-05-03 17:18
hi, this looks like a build error. can you post the output of `go env`?

**Comment by MarcoLucidi01** [comment] 2024-01-28 21:14
closing as i wasn't able to reproduce this and op didn't provide additional info.

**Closed by MarcoLucidi01** 2024-01-28 21:14 UTC
